// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dvanjyclijkibikfvagl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2YW5qeWNsaWpraWJpa2Z2YWdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNjYwNTAsImV4cCI6MjA2Mjc0MjA1MH0.Dv26rQqtPZrgBCfUknPiXFbVAKZjIWYulIa4srlasZk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);